export const GET_NAV_ITEMS = "GET_NAV_ITEMS";
export const SET_NAV_ITEMS = "SET_NAV_ITEMS";
export const ON_CLICK_HANDLER = "ON_CLICK_HANDLER";
export const LOAD_PAGE_ONE = "LOAD_PAGE_ONE";
export const SET_PAGE_ONE_CONTENT = "SET_PAGE_ONE_CONTENT";
export const LOAD_PAGE_TWO = "LOAD_PAGE_TWO";
export const SET_PAGE_TWO_CONTENT = "SET_PAGE_TWO_CONTENT";
export const CONECTION_FAILED = "CONECTION_FAILED";

